/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ratwnpugnptmfplezgve"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhdHducHVnbnB0bWZwbGV6Z3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzODA5OTEsImV4cCI6MjA4Njk1Njk5MX0.nObBgBLXmg9ti-oIyKt65DBQH9Ig5F5n0ecX-g3nLtE"